name: Podman CI

on:
  push:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Podman
      run: |
          sudo apt-get update
          sudo apt-get install -y podman
      
    - name: Authenticate with GitHub Container Registry
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin || exit 1

    - name: Build the Podman image
      run: podman build . --file Dockerfile --tag risk-assessment:${{ github.sha }}

    - name: Push the Podman image
      run: |
        podman push risk-assessment ghcr.io/${{ github.repository }}/risk-assessment:${{ github.sha }}
        podman push risk-assessment ghcr.io/${{ github.repository }}/risk-assessment:latest

