name: Podman and Singularity CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Install Podman
    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    # Install Singularity
    - name: Install Singularity
      run: |
        sudo apt-get install -y singularity-container

    # Build the Podman image
    - name: Build the Podman image
      run: podman build . --file Dockerfile --tag risk-assessment:$(date +%s)

    # Convert Podman image to Singularity image
    - name: Save the podman image as a tar file
      run: |
        podman save risk-assessment:$(date +%s) -o risk-assessment.tar

    # Upload Singularity image as an artifact
    - name: Upload Podman Image
      uses: actions/upload-artifact@v4
      with:
        name: podman-image
        path: risk-assessment.tar
